//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalcazzSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizaciones
    {
        public int IdProyecto { get; set; }
        public string Usuario { get; set; }
        public short idNivelAcceso { get; set; }
    
        public virtual NivelAccesos NivelAccesos { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
